name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish webextension
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Build Chrome extension
      run: |
        pnpm install
        pnpm build:chrome
    - name: Check Chrome Web Store review status
      id: check_review
      run: |
        # Get OAuth2 token
        TOKEN=$(curl -s \
          -d client_id="${{ secrets.CLIENT_ID }}" \
          -d client_secret="${{ secrets.CLIENT_SECRET }}" \
          -d refresh_token="${{ secrets.REFRESH_TOKEN }}" \
          -d grant_type=refresh_token \
          https://oauth2.googleapis.com/token | jq -r .access_token)

        # Query extension status
        STATUS=$(curl -s \
          -H "Authorization: Bearer $TOKEN" \
          -H "x-goog-api-version: 2" \
          "https://www.googleapis.com/chromewebstore/v1.1/items/mfmegmfbgapnopkjfocndlkbdapaogam" | jq -r .status[])

        echo "Extension status: $STATUS"

        if [[ "$STATUS" == *"IN_REVIEW"* ]]; then
          echo "Ongoing review detected, cancelling review..."
          curl -s -X POST \
            -H "Authorization: Bearer $TOKEN" \
            -H "x-goog-api-version: 2" \
            "https://www.googleapis.com/chromewebstore/v1.1/items/mfmegmfbgapnopkjfocndlkbdapaogam/publish?publishTarget=default&action=abort"
        else
          echo "No ongoing review."
        fi
    - name: Upload & release Chrome extension
      uses: mnao305/chrome-extension-upload@v5.0.0
      with:
        file-path: dist.zip
        extension-id: mfmegmfbgapnopkjfocndlkbdapaogam
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}
      continue-on-error: true
    - name: Build Firefox extension
      run: |
        pnpm build:firefox
    - name: Generate source zip
      run: |
        pnpm source
    - name: Upload & release Firefox extension
      uses: wdzeng/firefox-addon@v1
      with:
        addon-guid: zen-hordes@franckdemoute.fr
        xpi-path: dist.zip
        self-hosted: false
        jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
        jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}
        source-file-path: source.zip
