name: Publish

on:
  push:
    tags:
      - '*'

jobs:
  build:
    name: Publish webextension
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [20]

    steps:
    - uses: actions/checkout@v4
    - name: Install pnpm
      uses: pnpm/action-setup@v4
      with:
        version: 10
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: ${{ matrix.node-version }}
        cache: 'pnpm'
    - name: Build Chrome extension
      run: |
        pnpm install
        pnpm build:chrome
    - name: Check for ongoing Chrome review
      run: |
        pnpm dlx chrome-webstore-upload-cli check \
          --extension-id=mfmegmfbgapnopkjfocndlkbdapaogam \
          --client-id="${{ secrets.CLIENT_ID }}" \
          --client-secret="${{ secrets.CLIENT_SECRET }}" \
          --refresh-token="${{ secrets.REFRESH_TOKEN }}" \
          > review_status.txt

        echo "=== chrome-webstore-upload-cli check output ==="
        cat review_status.txt

        if grep -q "IN_REVIEW" review_status.txt; then
          echo "Ongoing review detected, aborting..."
          pnpm dlx chrome-webstore-upload-cli abort \
            --extension-id=mfmegmfbgapnopkjfocndlkbdapaogam \
            --client-id="${{ secrets.CLIENT_ID }}" \
            --client-secret="${{ secrets.CLIENT_SECRET }}" \
            --refresh-token="${{ secrets.REFRESH_TOKEN }}"
        else
          echo "No ongoing review."
        fi

    - name: Upload & release Chrome extension
      uses: mnao305/chrome-extension-upload@v5.0.0
      with:
        file-path: dist.zip
        extension-id: mfmegmfbgapnopkjfocndlkbdapaogam
        client-id: ${{ secrets.CLIENT_ID }}
        client-secret: ${{ secrets.CLIENT_SECRET }}
        refresh-token: ${{ secrets.REFRESH_TOKEN }}
      continue-on-error: true
    - name: Build Firefox extension
      run: |
        pnpm build:firefox
    - name: Generate source zip
      run: |
        pnpm source
    - name: Upload & release Firefox extension
      uses: wdzeng/firefox-addon@v1
      with:
        addon-guid: zen-hordes@franckdemoute.fr
        xpi-path: dist.zip
        self-hosted: false
        jwt-issuer: ${{ secrets.FIREFOX_JWT_ISSUER }}
        jwt-secret: ${{ secrets.FIREFOX_JWT_SECRET }}
        source-file-path: source.zip
